name: jupyter-earth

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - geopandas
  - hdf5
  - h5py
  - ipyleaflet
  - ipympl
  - ipywidgets
  - jupyter-book=0.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - seaborn
  - xarray
  - pip:
    - icepyx
