name: jupyter-earth

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - ipympl
  - jupyter-book=0.10
  - pip
  - hdf5
  - h5py
  - xarray
  - pip:
    - icepyx
