title          : Jupyter Meets the Earth - Toy research workflows
author         : The Jupyter Meets the Earth Team 
copyright      : "2021"  
logo           : images/jupyter-earth.png

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://geostacks.github.io/toy-research-workflow

bibtex_bibfiles:
 - refs.bib

bibtex_reference_style: author_year

repository:
  url: https://github.com/geostacks/toy-research-workflow
  branch: main
  path_to_book: docs

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  # thebe: true
  
execute:
  execute_notebooks : 'false'
  timeout           : 30
  allow_errors      : false